workspace = { members = [ "modules/*"] }
[package]
name = "carmine_engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
carmine_exports = { path = "modules/carmine_exports" }
