[package]
name = "carmine_events"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
carmine_errors = { path = "../carmine_errors/" }
